name: Deploy Hexo
on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master

    - uses: actions/setup-node@v3

    - name: Installation
      run: |
        npm install
        npm install -g hexo-cli gulp  

    - name: Generate
      run: hexo generate

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public